/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import java.awt.EventQueue;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author dam203
 */
public class Ventana extends javax.swing.JFrame implements Observer{
    /**
     * Creates new form Ventana
     */
    MedicionTiempo mt;
    Thread[] threads;
    public Ventana() {
       initComponents();
       iniciarCalculos();
       crearDialogo();
    }
    
    private void iniciarCalculos(){
       Drop d = new Drop();
       Producer p1 = new Producer(d, "p1");
       p1.addObserver(this);
       Thread tp1 = new Thread(p1, "tp1");
       Producer p2 = new Producer(d, "p2");
       p2.addObserver(this);
       Thread tp2 = new Thread(p2, "tp2");
       Producer p3 = new Producer(d, "p3");
       p3.addObserver(this);
       Thread tp3 = new Thread(p3, "tp3");
       Consumer c1 = new Consumer(d, "c1");
       c1.addObserver(this);
       Thread tc1 = new Thread(c1, "tc1");
       Consumer c2 = new Consumer(d, "c2");
       c2.addObserver(this);
       Thread tc2 = new Thread(c2, "tc2");
       Thread[] ts = {tp1, tp2, tp3, tc1, tc2};
       this.mt = new MedicionTiempo(ts);
       this.mt.addObserver(this);
       Thread tmt = new Thread(this.mt);
       tmt.start();
       threads = ts;
    }
    
    private void crearDialogo() {
        //TODO cambiar mensaje y añadir distintas medidas
        int respuesta = JOptionPane.showOptionDialog( null,"Do you want to change the units to ml/h and ml/person?",
                                                        "29BPDJ - Measurement units",JOptionPane.YES_NO_CANCEL_OPTION,
                                                        JOptionPane.QUESTION_MESSAGE,null,// null para icono por defecto.
                                                        new Object[] { "Yes", "No"},"Yes");
        
        if (respuesta == JOptionPane.YES_OPTION) {
            //cambiar unidades
        } else {
            //mantener uniaddes
        }
        mt.setStart(true);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProducer = new javax.swing.JTextArea();
        jTextAreaProducer.setEditable(false);
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaJornadas = new javax.swing.JTextArea();
        jTextAreaProducer.setEditable(false);
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaConsumer = new javax.swing.JTextArea();
        jTextAreaConsumer.setEditable(false);
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaEmpleados = new javax.swing.JTextArea();
        jTextAreaConsumer.setEditable(false);
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("29BPDJ");

        jLabel1.setText("Producer:");

        jTextAreaProducer.setColumns(20);
        jTextAreaProducer.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProducer);

        jLabel4.setText("Jornadas:");

        jTextAreaJornadas.setColumns(20);
        jTextAreaJornadas.setRows(5);
        jScrollPane3.setViewportView(jTextAreaJornadas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setText("Consumer:");

        jTextAreaConsumer.setColumns(20);
        jTextAreaConsumer.setRows(5);
        jScrollPane2.setViewportView(jTextAreaConsumer);

        jTextAreaEmpleados.setColumns(20);
        jTextAreaEmpleados.setRows(5);
        jScrollPane4.setViewportView(jTextAreaEmpleados);

        jLabel5.setText("Empleados:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("Execution Time:");

        jLabelTime.setText("0 ms");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelTime))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    @Override
    public void update(Observable o, Object arg) {
        String observ = o.getClass().getSimpleName();
        
        if(observ.equalsIgnoreCase("MedicionTiempo")){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                        for(Object j : Recursos.jornadas){
                        Jornada jor = (Jornada) j;
                        if(jor.getIdParque() > 0){
                            jTextAreaJornadas.append("ID: "+jor.getIdParque() + " - Horas: "+jor.getNumVisitantes()+"\n");
                        }
                    }
                    for(Object e : Recursos.empleados){
                        Empleado emp = (Empleado) e;
                        if(emp.getId() > 0){
                            jTextAreaEmpleados.append("ID: "+emp.getId() + " - Horas Totales: "+emp.getVisitantesTotales()+"\n");
                        }
                    }
                    jLabelTime.setText(arg.toString());
                }
            });
        }else if (observ.equalsIgnoreCase("Consumer")){
            if(arg != null){
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        jTextAreaConsumer.append(arg.toString()+"\n");
                    }
                });
            }else{
                interrumpirThreads();
            }
        }else if (observ.equalsIgnoreCase("Producer")){
            if(arg != null){
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        jTextAreaProducer.append(arg.toString()+ "\n");
                    }
                });
            }else{
                interrumpirThreads();
            }            
        }else{
            if(arg == null){
                interrumpirThreads();
            }
        }
    }

    synchronized void interrumpirThreads() {
        for (Thread t : this.threads) {
            if (t.isAlive()) {
                t.interrupt();
                System.out.println("thread: " + t.getName());
            }
        }
    } 
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaConsumer;
    private javax.swing.JTextArea jTextAreaEmpleados;
    private javax.swing.JTextArea jTextAreaJornadas;
    private javax.swing.JTextArea jTextAreaProducer;
    // End of variables declaration//GEN-END:variables
}
